import { Poppins } from 'next/font/google';
import '../../styles/globals.css';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Theme from '../../components/Theme';

const inter = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"]
})

export const metadata = {
  title: 'Travel Website with NextJS 13 Beta',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link rel="icon" href="./plane1.jpg" />
      </head>
      <body className={inter.className}>
        <Theme />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
